/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppBreadcrumb: typeof import('./components/AppBreadcrumb.vue')['default']
    AppPage: typeof import('./components/AppPage.vue')['default']
    EmojioneMoneyWithWings: typeof import('~icons/emojione/money-with-wings')['default']
    FluentAddCircle24Regular: typeof import('~icons/fluent/add-circle24-regular')['default']
    GettingStarted: typeof import('./components/GettingStarted.vue')['default']
    HelloApi: typeof import('./components/HelloApi.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LogosDigitalOcean: typeof import('~icons/logos/digital-ocean')['default']
    LogosJamstackIcon: typeof import('~icons/logos/jamstack-icon')['default']
    LogosTailwindcssIcon: typeof import('~icons/logos/tailwindcss-icon')['default']
    LogosTypescriptIcon: typeof import('~icons/logos/typescript-icon')['default']
    LogosVisualStudio: typeof import('~icons/logos/visual-studio')['default']
    LogosVisualStudioCode: typeof import('~icons/logos/visual-studio-code')['default']
    LogosVitejs: typeof import('~icons/logos/vitejs')['default']
    LogosVue: typeof import('~icons/logos/vue')['default']
    MarkdownPage: typeof import('./components/MarkdownPage.vue')['default']
    MdiAccountCircle: typeof import('~icons/mdi/account-circle')['default']
    MdiArrowLeftThin: typeof import('~icons/mdi/arrow-left-thin')['default']
    MdiCheck: typeof import('~icons/mdi/check')['default']
    MdiCheckboxBlankCircleOutline: typeof import('~icons/mdi/checkbox-blank-circle-outline')['default']
    MdiCheckCircle: typeof import('~icons/mdi/check-circle')['default']
    MdiChevronLeft: typeof import('~icons/mdi/chevron-left')['default']
    MdiChevronRight: typeof import('~icons/mdi/chevron-right')['default']
    MdiCodeTags: typeof import('~icons/mdi/code-tags')['default']
    MdiCurrencyUsd: typeof import('~icons/mdi/currency-usd')['default']
    MdiHome: typeof import('~icons/mdi/home')['default']
    MdiShieldAccount: typeof import('~icons/mdi/shield-account')['default']
    MdiSquareEditOutline: typeof import('~icons/mdi/square-edit-outline')['default']
    MdiTrashCanOutline: typeof import('~icons/mdi/trash-can-outline')['default']
    NavFooter: typeof import('./components/NavFooter.vue')['default']
    NavHeader: typeof import('./components/NavHeader.vue')['default']
    NavItem: typeof import('./components/NavItem.vue')['default']
    NavLink: typeof import('./components/NavLink.vue')['default']
    NotoPineapple: typeof import('~icons/noto/pineapple')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShellCommand: typeof import('./components/ShellCommand.vue')['default']
    SrcLink: typeof import('./components/SrcLink.vue')['default']
  }
}
