// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ApiForm: typeof import('./components/form/ApiForm.vue')['default']
    AppBreadcrumb: typeof import('./components/AppBreadcrumb.vue')['default']
    AppPage: typeof import('./components/AppPage.vue')['default']
    Checkbox: typeof import('./components/form/Checkbox.vue')['default']
    ErrorSummary: typeof import('./components/form/ErrorSummary.vue')['default']
    FormLoading: typeof import('./components/form/FormLoading.vue')['default']
    GettingStarted: typeof import('./components/GettingStarted.vue')['default']
    HelloApi: typeof import('./components/HelloApi.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    InputDescription: typeof import('./components/form/InputDescription.vue')['default']
    LogosTailwindcssIcon: typeof import('~icons/logos/tailwindcss-icon')['default']
    LogosTypescriptIcon: typeof import('~icons/logos/typescript-icon')['default']
    LogosVitejs: typeof import('~icons/logos/vitejs')['default']
    LogosVue: typeof import('~icons/logos/vue')['default']
    MarkdownPage: typeof import('./components/MarkdownPage.vue')['default']
    MdiAccountCircle: typeof import('~icons/mdi/account-circle')['default']
    MdiAlertCircleOutline: typeof import('~icons/mdi/alert-circle-outline')['default']
    MdiArrowLeftThin: typeof import('~icons/mdi/arrow-left-thin')['default']
    MdiCheck: typeof import('~icons/mdi/check')['default']
    MdiChevronRight: typeof import('~icons/mdi/chevron-right')['default']
    MdiCloseCircle: typeof import('~icons/mdi/close-circle')['default']
    MdiHome: typeof import('~icons/mdi/home')['default']
    MdiShieldAccount: typeof import('~icons/mdi/shield-account')['default']
    NavFooter: typeof import('./components/NavFooter.vue')['default']
    NavHeader: typeof import('./components/NavHeader.vue')['default']
    NavItem: typeof import('./components/NavItem.vue')['default']
    NavLink: typeof import('./components/NavLink.vue')['default']
    PrimaryButton: typeof import('./components/form/PrimaryButton.vue')['default']
    SecondaryButton: typeof import('./components/form/SecondaryButton.vue')['default']
    ShellCommand: typeof import('./components/ShellCommand.vue')['default']
    TextInput: typeof import('./components/form/TextInput.vue')['default']
  }
}

export { }
